[2023-05-30T07:33:08.122+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: smtp_test_dag.send_email manual__2023-05-30T07:23:14.545871+00:00 [queued]>
[2023-05-30T07:33:08.134+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: smtp_test_dag.send_email manual__2023-05-30T07:23:14.545871+00:00 [queued]>
[2023-05-30T07:33:08.134+0000] {taskinstance.py:1308} INFO - Starting attempt 4 of 4
[2023-05-30T07:33:08.166+0000] {taskinstance.py:1327} INFO - Executing <Task(EmailOperator): send_email> on 2023-05-30 07:23:14.545871+00:00
[2023-05-30T07:33:08.173+0000] {standard_task_runner.py:57} INFO - Started process 202 to run task
[2023-05-30T07:33:08.180+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'smtp_test_dag', 'send_email', 'manual__2023-05-30T07:23:14.545871+00:00', '--job-id', '138', '--raw', '--subdir', 'DAGS_FOLDER/smtp_test.py', '--cfg-path', '/tmp/tmpwh77ta_6']
[2023-05-30T07:33:08.182+0000] {standard_task_runner.py:85} INFO - Job 138: Subtask send_email
[2023-05-30T07:33:08.262+0000] {task_command.py:410} INFO - Running <TaskInstance: smtp_test_dag.send_email manual__2023-05-30T07:23:14.545871+00:00 [running]> on host 6ce4f1a09d96
[2023-05-30T07:33:08.402+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='smtp_test_dag' AIRFLOW_CTX_TASK_ID='send_email' AIRFLOW_CTX_EXECUTION_DATE='2023-05-30T07:23:14.545871+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-05-30T07:23:14.545871+00:00'
[2023-05-30T07:33:08.424+0000] {logging_mixin.py:149} WARNING - /home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py:152 RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
[2023-05-30T07:33:08.424+0000] {email.py:268} INFO - Email alerting: attempt 1
[2023-05-30T07:33:09.156+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/email.py", line 87, in execute
    custom_headers=self.custom_headers,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 91, in send_email
    **kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 152, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 279, in send_mime_email
    smtp_conn.login(smtp_user, smtp_password)
  File "/usr/local/lib/python3.7/smtplib.py", line 702, in login
    "SMTP AUTH extension not supported by server.")
smtplib.SMTPNotSupportedError: SMTP AUTH extension not supported by server.
[2023-05-30T07:33:09.168+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=smtp_test_dag, task_id=send_email, execution_date=20230530T072314, start_date=20230530T073308, end_date=20230530T073309
[2023-05-30T07:33:09.191+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 138 for task send_email (SMTP AUTH extension not supported by server.; 202)
[2023-05-30T07:33:09.235+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-05-30T07:33:09.275+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
